github_target_url: https://github.com/kigma00/CCIT_GoCD_PipelineCode
codevuln_group: defaultGroup

#yaml test
yaml_template = f'''
format_version: 10
environment:
  seceret:
pipelines:
  pipeline-test_1:
    group: {codevuln_group}
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-d86ad4c:
        git: {github_target_url}
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - stage-test_1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job-test_1:
            timeout: 0
            tasks:
              - exec:
                arguments:
                  - Upload test
                command: echo
                run_if: passed
'''

with open(f'{github_target_url}.yaml',  'w') as w:
  w.write(yaml_template)

