
format_version: 10
pipelines:
  mongodb:
    group: gocd_test
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/mongodb/mongo
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - mongodb_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          mongodb_job:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
    
