format_version: 10
pipelines:
  GoCD_test_Pipe:
    group: codeQL
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-fdee270:
        git: https://github.com/kigma00/CCIT_GoCD_PipelineCode
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - codeQL_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          codeql_job:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
    - build_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          build_job:
            timeout: 0
            tasks:
            - exec:
                command: echo
                arguments: ["Building the project..."]
                run_if: passed
            - exec:
                command: make
                run_if: passed
    - test_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          test_job:
            timeout: 0
            tasks:
            - exec:
                command: echo
                arguments: ["Running tests..."]
                run_if: passed
            - exec:
                command: make
                arguments: ["test"]
                run_if: passed
    - deploy_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          deploy_job:
            timeout: 0
            tasks:
            - exec:
                command: echo
                arguments: ["Deploying the project..."]
                run_if: passed
            - exec:
                command: ./deploy.sh
                run_if: passed
