---
format_version: 10
pipelines:
  pipe_test:
    group: defaultGroup
    label_template: "${COUNT}"
    lock_behavior: none
    display_order: -1
    materials:
      - git:  # 해시 형식으로 수정
          url: "https://github.com/kigma00/CCIT_GoCD_PipelineCode"
          shallow_clone: false
          auto_update: true
          branch: main
    stages:
      - name: stage_test
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          - name: jobntasks_test
            timeout: 0
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - "test"
                  run_if: passed

environments:
  dev:
    pipelines:
      - pipe_test
